# Generated by Django 3.2.7 on 2022-02-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='defaultProfilePic.jpg', upload_to='profile_pics'),
        ),
    ]
