# Generated by Django 3.2.7 on 2022-02-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_alter_blog_blog_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
